# Generated by Django 5.2.14 on 2026-06-04 12:03

import apps.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_cancelled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.jobs.models._job_image_path),
        ),
    ]
