# Generated by Django 5.2.14 on 2026-06-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_image_path_by_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='images_purged',
            field=models.BooleanField(default=False),
        ),
    ]
