# Generated by Django 6.0.6 on 2026-08-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_completed_at_images_purged'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='conf',
            field=models.FloatField(default=0.85),
        ),
        migrations.AddField(
            model_name='job',
            name='marker_type',
            field=models.CharField(choices=[('all', 'Auto-detect'), ('marker', 'Marker'), ('quadrat', 'Quadrat')], default='all', max_length=20),
        ),
    ]
