# Generated by Django 6.0.6 on 2026-08-20 03:46

import apps.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_conf_job_marker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='overlay_thumbnail',
            field=models.ImageField(blank=True, upload_to=apps.jobs.models._job_thumb_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Configure'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
