# Generated by Django 6.0.6 on 2026-09-22 03:05

import apps.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobimage_overlay_thumbnail_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=apps.jobs.models._job_raw_thumb_path),
        ),
    ]
