# Generated by Django 6.0.6 on 2026-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('local', 'Local Upload'), ('google_drive', 'Google Drive'), ('sample', 'Sample Images')], max_length=20),
        ),
    ]
